// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: caffe2_legacy.proto

#include "caffe2_legacy.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace caffe2 {
}  // namespace caffe2
void InitDefaults_caffe2_5flegacy_2eproto() {
}

constexpr ::google::protobuf::Metadata* file_level_metadata_caffe2_5flegacy_2eproto = nullptr;
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors_caffe2_5flegacy_2eproto[1];
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_caffe2_5flegacy_2eproto = nullptr;
const ::google::protobuf::uint32 TableStruct_caffe2_5flegacy_2eproto::offsets[1] = {};
static constexpr ::google::protobuf::internal::MigrationSchema* schemas = nullptr;
static constexpr ::google::protobuf::Message* const* file_default_instances = nullptr;

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_caffe2_5flegacy_2eproto = {
  {}, AddDescriptors_caffe2_5flegacy_2eproto, "caffe2_legacy.proto", schemas,
  file_default_instances, TableStruct_caffe2_5flegacy_2eproto::offsets,
  file_level_metadata_caffe2_5flegacy_2eproto, 0, file_level_enum_descriptors_caffe2_5flegacy_2eproto, file_level_service_descriptors_caffe2_5flegacy_2eproto,
};

const char descriptor_table_protodef_caffe2_5flegacy_2eproto[] =
  "\n\023caffe2_legacy.proto\022\006caffe2*J\n\rLegacyP"
  "adding\022\n\n\006NOTSET\020\000\022\t\n\005VALID\020\001\022\010\n\004SAME\020\002\022"
  "\030\n\024CAFFE_LEGACY_POOLING\020\003"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_caffe2_5flegacy_2eproto = {
  false, InitDefaults_caffe2_5flegacy_2eproto, 
  descriptor_table_protodef_caffe2_5flegacy_2eproto,
  "caffe2_legacy.proto", &assign_descriptors_table_caffe2_5flegacy_2eproto, 105,
};

void AddDescriptors_caffe2_5flegacy_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_caffe2_5flegacy_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_caffe2_5flegacy_2eproto = []() { AddDescriptors_caffe2_5flegacy_2eproto(); return true; }();
namespace caffe2 {
const ::google::protobuf::EnumDescriptor* LegacyPadding_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&assign_descriptors_table_caffe2_5flegacy_2eproto);
  return file_level_enum_descriptors_caffe2_5flegacy_2eproto[0];
}
bool LegacyPadding_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace caffe2
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
